### ISSUE TITLE
Unable to run on 6gb GPU

### ISSUE THREAD

**Issue by Agarwal-Saurabh** [Moving-AI/virtual-walk#18]
Is there a way to run on low gpu memory, it says memory full ??

**Comment by javirk** [comment]
That will probably be because of PoseNet, which uses Resnet. Could you try with Mobile Net? Just make sure mobilenet model is downloaded in "models/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite" and edit config_resnet's backbone option to use mobilenet (i.e. backbone: mobilenet).

**Comment by gontxomde** [comment]
Inactive
